wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>/", views.show_entry, name="show_entry"),
    path("search", views.search, name="search"),
    path("create", views.create, name="create"),
    path("edit/<str:name>", views.edit, name="edit"),
    path("random_page", views.random_page, name="random_page")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django import forms
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.contrib import messages

from . import util

import random

class SearchForm(forms.Form):
    q = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': 'Search Encyclopedia'}))

class NewPageForm(forms.Form):
    title = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': 'Title'}))
    content = forms.CharField(label="",widget=forms.Textarea(attrs={'rows': '5', 'cols': '10'}))


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "searchform": SearchForm()
    })

def show_entry(request, entry):
      
    if not util.get_entry(entry):
        return render(request, "encyclopedia/error.html", {
            "searchform": SearchForm()
        })

    return render(request, "encyclopedia/entry.html", {
        "entry": util.get_entry(entry),
        "name": entry,
        "searchform": SearchForm()
    })

def search(request):
    form = SearchForm(request.GET)
    if form.is_valid():
        q = form.cleaned_data["q"]
        includesq = []
        for entry in util.list_entries():
            if q == entry:
                break
            elif q in entry:
                includesq.append(entry)

        if len(includesq) != 0:
            return render(request, "encyclopedia/index.html", {
            "entries": includesq,
            "searchform": SearchForm()
            })
        else:
            # return redirect('encyclopedia:show_entry', entry=q)
            return redirect('encyclopedia:show_entry', q)

def create(request):

    if request.method == "POST":
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            if title in util.list_entries():
                messages.warning(request, 'Sorry, the title is not available.')
                return render(request, "encyclopedia/create.html", {
                "searchform": SearchForm(),
                "newpageform": form
            })
            else:
                util.save_entry(title, content)
                return redirect('encyclopedia:show_entry', title)

    return render(request, "encyclopedia/create.html", {
        "searchform": SearchForm(),
        "newpageform": NewPageForm()
    })

def edit(request, name):

    if request.method == "POST":
        data = {"title": name, "content": request.POST['content']}
        form = NewPageForm(data)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            util.save_entry(title, content)
            return redirect('encyclopedia:show_entry', title)
            
    data = {"title": name, "content": util.get_entry(name)}
    form = NewPageForm(data)

    return render(request, "encyclopedia/edit.html", {
        "searchform": SearchForm(),
        "form": form,
        "name": name
    })

def random_page(request):

    entry = random.choice(util.list_entries())

    return render(request, "encyclopedia/entry.html", {
        "entry": util.get_entry(entry),
        "name": entry,
        "searchform": SearchForm()
    })

wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>
    <div>
        {% include 'encyclopedia/messages.html' %}
        <form action="{% url 'encyclopedia:create' %}" method="post">
            {% csrf_token %}
            {{ newpageform.title }}<br>
            {{ newpageform.content }}<br>
            <input type="submit" value="Save">
        </form>
    </div>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block body %}
    <h1>Edit Page</h1>
    <div>
        <form action="{% url 'encyclopedia:edit' name %}" method="post">
            {% csrf_token %}
            {{ form.content }}<br>
            <input type="submit" value="Save">
        </form>
    </div>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}
{% load markdown_extras %}

{% block title %}
    {{ name }}
{% endblock %}

{% block body %}

{{ entry | markdown | safe }}
<form action="{% url 'encyclopedia:edit' name %}">
    {% csrf_token %}
    <input type="submit" value="Edit"></input>
</form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Page Not Found
{% endblock %}

{% block body %}

<h1>Error: the page was not found!</h1>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:show_entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}">
                    {{ searchform }}
                    <!-- <input class="search" type="text" name="q" placeholder="Search Encyclopedia"> -->
                    <input type="submit" hidden>
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-dismissible alert-warning">
      <button type="button" class="close" data-dismiss="alert">
      ×
      </button>
      <strong>{{message}}</strong>
    </div>
 {% endfor %}
{% endif %}